name: Bandit
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
      - name: Run Bandit
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: '--configfile .bandit -x .tox,docs,tests/.coveragerc,.dockerignore,_build -s B101,B105,B108,B320,B410,B501'

