name: Bandit
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Run Bandit
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: '--configfile .bandit -x .tox,docs,tests/.coveragerc,.dockerignore,_build -s B101,B105,B108,B320,B410,B501'

